/**
 * Cypress config — generated by Contract Kit Creator (Anchor 3).
 *
 * Test Replay produces forensic-grade evidence (full DOM + network +
 * console) that non-coders can review. Failure-only screenshots keep
 * artifact size manageable.
 *
 * Project: {{projectName}}
 * Generated: {{generatedAt}}
 */

import { defineConfig } from "cypress"

export default defineConfig({
	e2e: {
		baseUrl: "{{baseURL}}",
		specPattern: "{{specPattern}}",
		supportFile: false,
		// Anchor 3 — forensic trace evidence
		video: true,
		videoCompression: 32,
		videoUploadOnPasses: false, // cost control
		screenshotOnRunFailure: true,
		screenshotsFolder: "cypress/screenshots",
		videosFolder: "cypress/videos",
		// Test Replay (cypress.io cloud) when CYPRESS_RECORD_KEY is set.
		experimentalStudio: false,
		experimentalRunAllSpecs: true,
		retries: {
			runMode: 2,
			openMode: 0,
		},
		viewportWidth: 1280,
		viewportHeight: 720,
	},
})
