/**
 * Playwright config — generated by Contract Kit Creator (Anchor 3).
 *
 * Trace evidence is forensic-grade: every failed test produces a `trace.zip`
 * containing screenshots, DOM snapshots, network calls, and console output.
 * Open with `npx playwright show-trace test-results/<name>/trace.zip`.
 *
 * Project: {{projectName}}
 * Generated: {{generatedAt}}
 */

import { defineConfig, devices } from "@playwright/test"

export default defineConfig({
	testDir: "{{testDir}}",
	timeout: 30_000,
	expect: {
		timeout: 5_000,
		toHaveScreenshot: {
			maxDiffPixelRatio: 0.01,
			threshold: 0.2,
			animations: "disabled",
		},
	},
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	workers: process.env.CI ? 1 : undefined,
	reporter: [
		["html", { outputFolder: "playwright-report", open: "never" }],
		["junit", { outputFile: "playwright-report/junit.xml" }],
		["list"],
	],
	outputDir: "test-results",
	use: {
		baseURL: "{{baseURL}}",
		// Anchor 3 — forensic trace evidence
		trace: "on-first-retry",
		screenshot: "only-on-failure",
		video: "retain-on-failure",
		actionTimeout: 10_000,
		navigationTimeout: 15_000,
	},
	projects: [
		{
			name: "chromium",
			use: { ...devices["Desktop Chrome"] },
		},
		{
			name: "firefox",
			use: { ...devices["Desktop Firefox"] },
		},
		{
			name: "webkit",
			use: { ...devices["Desktop Safari"] },
		},
	],
})
